### ISSUE TITLE
Instructions to integrate with Saleor?

### ISSUE THREAD

**Issue by rohanrajpal** [itswadesh/svelte-commerce#15]
**Is your feature request related to a problem? Please describe.**
I want to integrate this frontend with [Saleor](https://saleor.io/api/)
**Describe the solution you'd like**
A simple readme with how to get started would be great!
Otherwise, just some resources on how to get started will also do.
**Describe alternatives you've considered**
I've tried to have a look at config.js, but I guess this frontend is using a REST API and Saleor uses GraphQL, I'm new to GraphQL and can't figure out the integration.

**Comment by itswadesh** [comment]
Hello Rohan,

You may need to use https://github.com/timhall/svelte-apollo

**Comment by rohanrajpal** [comment]
> Hello Rohan,
> 
> You may need to use https://github.com/timhall/svelte-apollo

Thanks!
