### ISSUE TITLE
Update Tailwind to v2

### ISSUE THREAD

**Issue by gevera** [itswadesh/svelte-commerce#16]
Hi. Are there any plans to switch to the newer version of TailwindCSS ?.  I use Sapper and Tailwind 2 in production and about to start a new e-commerce project. Before I begin, was looking for ready-made options. Your project is almost perfect. Cheers

**Comment by itswadesh** [comment]
Hello Gevera, There is a plan for upgrade but I am waiting for sveltekit to release. I will upgrade both at once. Thanks for following the project.

**Comment by gevera** [comment]
> Hello Gevera, There is a plan for upgrade but I am waiting for sveltekit to release. I will upgrade both at once. Thanks for following the project.

I think everybody is excited and waiting for sveltkit. Then you might want to close this issue and open a project roadmap so everybody can follow it :) Best regards
