### ISSUE TITLE
[filtering page] APPLY button is not shown at the bottom of a screen on an Android phone 

### ISSUE THREAD

**Issue by andrei-volkau** [itswadesh/svelte-commerce#31]
**Describe the bug**
**APPLY** button is not shown at the bottom of a screen on an Android phone. I am talking about the "filtering" page.

**To Reproduce**
1. Go to 'https://svelte-commerce.litekart.in/search' from your Android smartphone
2. Click on 'filter'

**Expected behavior**
APPLY button is shown at the bottom of the screen

**Screenshots**
![photo_2022-01-16_22 08 13_1_50](https://user-images.githubusercontent.com/12778567/149674437-8716a324-9e17-4f15-9895-304bea3c1eca.jpeg)

**Smartphone (please complete the following information):**
 - Device: Android smartphone
 - OS: Android 10
 - Browser: Chrome
 - Version: 96.0.4664.92

**Comment by itswadesh** [comment]
Hi Andrei,

Thank you so much for raising the issue. I will have a look and fix it as soon.

**Comment by JugurthaMoad** [comment]
Hi @itswadesh, if this issue is available, i would like to work on

**Comment by itswadesh** [comment]
Hi @JugurthaMoad Thanks for the support offer. Anyway I have moved the filter to the top. I guess this issue is already resoved. 
You are welcome to contribute any way. ❤️

**Comment by JugurthaMoad** [comment]
You're welcome @itswadesh
