### ISSUE TITLE
npm i (8.19.1) not able to run dev

### ISSUE THREAD

**Issue by imrosun** [itswadesh/svelte-commerce#44]
Not able to run dev
Not able to install dependencies fully on npm version 8.19.1

Errors which I have faced:
npm ERR! syscall read
npm ERR! errno -4077
npm ERR! network read ECONNRESET
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
npm ERR! A complete log of this run can be found in:
npm ERR!

I have tried  
- npm i
- npm install vite
- npm config set fetch-retry-mintimeout 20000
- npm config set fetch-retry-maxtimeout 120000

How can I start using? 
Should I try going back to npm previous version?
Any suggestion would be appreciated

**Comment by itswadesh** [comment]
Hi I guess you are probably missing the following step
``` Make a copy of .env.example and rename to .env ```
