### ISSUE TITLE
Link to documentation

### ISSUE THREAD

**Issue by jruiz94** [itswadesh/svelte-commerce#53]
Hi sorry to disturb you this looks like an amazing project but I was wondering if there's any link to documentation on how can I integrate this with a MedusaJS backend. I can see some variable defined in the .env.example but I also see other backend solutions so I don't know if I should delete those or how should I proceed/possible caveats etc

Thanks in advance

BTW I know it's not ideal to open an issue for this but I couldn't see any way to reach out to you to ask this question, apologies.

**Comment by itswadesh** [comment]
Hi,

Based on your request I have made a quick docs https://github.com/itswadesh/svelte-commerce/blob/master/docs/medusa.md

+ made a big change on service modularization so that it will be easy for you to integrate Medusajs from only 1 directory

**Comment by jruiz94** [comment]
Perfect!! Thanks a ton I'll check it when I have some time, this project looks amazing!
