### ISSUE TITLE
What is the docker compose.yaml

### ISSUE THREAD

**Issue by Felmon** [itswadesh/svelte-commerce#60]
What is the best compose.yaml if I deploy using docker compose? Because I have to use woocommerce, I need to modify some configurations

**Comment by Felmon** [comment]
And after linking to woocomerce, is there a backend to customize the theme?

**Comment by itswadesh** [comment]
Can we have a short call, that way it will be easier to understand the exact requirement

**Comment by Felmon** [comment]
Is there a specific woocommerce association guide? I tried to change the woocommerce-related configuration of .env and src/lib/services/index.ts but this error occurred: 500 An unexpected error occurred. We're working on it.

**Comment by itswadesh** [comment]
Can you pull latest updates, it's working my side now.
