### ISSUE TITLE
Fix reel video page

### ISSUE THREAD

**Issue by itswadesh** [itswadesh/svelte-commerce#68]

**Comment by raunakhajela** [comment]
Could you please share more info on what issue we talking about here?

**Comment by itswadesh** [comment]
Hi @raunakhajela 
This issue here is about fixing the following page, it has some UX issues

https://demo.litekart.in/reel

**Comment by leorsousa05** [comment]
I oppened a pull request for it: #76

**Comment by leorsousa05** [comment]
I think it's just close this issue. The #76 already fix with the new icons and setup, the only thing needed to finish is approving the other check.

**Comment by leorsousa05** [comment]
Yeah, i'll open a pull request with it

**Comment by leorsousa05** [comment]
Hey @itswadesh i also found out that the videos doesn't have audio. You have the videos with audio?

**Comment by itswadesh** [comment]
The reels module is now working fine. Hence closing it.
