### ISSUE TITLE
Error 500 when deployed to vercel/netlify

### ISSUE THREAD

**Issue by teewebsites** [itswadesh/svelte-commerce#77]
Getting Error 500 when deployed to vercel/netlify

**To Reproduce**
1. click the the deploy to netlify or the deploy to vercel button on the github repo
2. wait for the site to be deployed on vercel or netlify
3. after the site is deployed successfully you will see the error 500 
4. no error to be found on the log of the deployment

**Expected behavior**
The main ecommerce page appearing on the deployed site

**Screenshots**

![Screenshot](https://github.com/itswadesh/svelte-commerce/assets/73783623/c80f9cd7-d75f-43e3-9294-eab47008eaae)

**Comment by itswadesh** [comment]
Hi, thank you for letting me know. I have added the instructions in the readme now.

just need to add 1 env variable into Vercel.

PUBLIC_LITEKART_DOMAIN=demo.litekart.in

**Comment by teewebsites** [comment]
Great, it worked on vercel but not on netlify it shows a different error.
