### ISSUE TITLE
Deployment to netlify is broken 

### ISSUE THREAD

**Issue by Frozen12** [itswadesh/svelte-commerce#89]
Deployment to netlify via Deploy button produce a faulty website.
The error message is 
![IMG_20240108_225505](https://github.com/itswadesh/svelte-commerce/assets/31291110/7545e356-5370-4a41-aecc-02891987e11d)

**Comment by Frozen12** [comment]
Function log from Netlify dashboard


Jan 9, 01:00:43 PM: INIT_START Runtime Version: nodejs:18.v18	Runtime Version ARN: arn:aws:lambda:us-east-2::runtime:d949ec0248c1b8fbc8cbc6df1c986e05fb933506b51d53be82d46f9a37125bea
Jan 9, 01:00:43 PM: 93c2447f ERROR  Invoke Error 	{"errorType":"Error","errorMessage":"unable to determine transport target for \"pino-pretty\"","stack":["Error: unable to determine transport target for \"pino-pretty\"","    at fixTarget (/var/task/node_modules/pino/lib/transport.js:144:13)","    at transport (/var/task/node_modules/pino/lib/transport.js:114:22)","    at normalizeArgs (/var/task/node_modules/pino/lib/tools.js:316:16)","    at pino (/var/task/node_modules/pino/pino.js:87:28)","    at file:///var/task/.netlify/server/chunks/logger.js:2:16","    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)"]}
Jan 9, 01:00:43 PM: 93c2447f Duration: 99.59 ms	Memory Usage: 79 MB	Init Duration: 207.71 ms

**Comment by itswadesh** [comment]
Thank you for the information. Issue has been fixed
