### ISSUE TITLE
I can't deplay on vercel

### ISSUE THREAD

**Issue by kevin25** [itswadesh/svelte-commerce#96]
I got the error as below 

<img width="892" alt="Screen Shot 2024-05-24 at 09 34 01" src="https://github.com/itswadesh/svelte-commerce/assets/2909982/89cecdb4-772e-4f19-b173-7966fd99a28a">

Please tell me how to fix it?

**Comment by itswadesh** [comment]
Thank you so much for raising this issue. It has been resolved now. 
Just need to deploy the master branch once more in vercel

**Comment by kevin25** [comment]
It works. Thank you

**Comment by kevin25** [comment]
Do you have online document?
